name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  # Your Registry Name
  ACR_NAME: vedranregistry99

jobs:
  # JOB 1: BUILD ALL IMAGES
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Login to Azure Container Registry
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 2. Build and Push VOTE
      - name: Build and Push Vote
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/vote:${{ github.sha }}

      # 3. Build and Push RESULT
      - name: Build and Push Result
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/result:${{ github.sha }}

      # 4. Build and Push WORKER
      - name: Build and Push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/worker:${{ github.sha }}

  # JOB 2: DEPLOY TO AKS
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: VotingApp
          cluster-name: VotingAppCluster

      # 5. Deploy and Swap Images
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            k8s-specifications/redis-deployment.yaml
            k8s-specifications/redis-service.yaml
            k8s-specifications/worker-deployment.yaml
            k8s-specifications/vote-deployment.yaml
            k8s-specifications/vote-service.yaml
            k8s-specifications/result-deployment.yaml
            k8s-specifications/result-service.yaml
            k8s-specifications/db-statefulset.yaml
            k8s-specifications/db-service-headless.yaml
            k8s-specifications/policy-deny-all.yaml
            k8s-specifications/policy-allow-vote-redis.yaml
            k8s-specifications/policy-allow-worker.yaml
            k8s-specifications/policy-allow-result-db.yaml
          # This replaces the images in the YAMLs with your newly built ones
          images: |
            ${{ env.ACR_NAME }}.azurecr.io/vote:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/result:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/worker:${{ github.sha }}