# JOB 2: DEPLOY TO AKS
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # 1. Login to Azure (for AKS access)
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Login to Registry 
      # The deploy action needs this to verify the images exist
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Connect to AKS Cluster
      - uses: azure/aks-set-context@v3
        with:
          resource-group: VotingApp
          cluster-name: VotingAppCluster

      # 4. Deploy Manifests & Swap Image
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            k8s-specifications/redis-deployment.yaml
            k8s-specifications/redis-service.yaml
            k8s-specifications/worker-deployment.yaml
            k8s-specifications/vote-deployment.yaml
            k8s-specifications/vote-service.yaml
            k8s-specifications/result-deployment.yaml
            k8s-specifications/result-service.yaml
            k8s-specifications/db-statefulset.yaml
            k8s-specifications/db-service-headless.yaml
            k8s-specifications/policy-deny-all.yaml
            k8s-specifications/policy-allow-vote-redis.yaml
            k8s-specifications/policy-allow-worker.yaml
            k8s-specifications/policy-allow-result-db.yaml
          images: |
            ${{ env.ACR_NAME }}.azurecr.io/vote:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/result:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/worker:${{ github.sha }}